---
default_stages: [pre-commit]
repos:
  # General Hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-toml
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: forbid-new-submodules
  # YAML Hooks
  - repo: https://github.com/google/yamlfmt.git
    rev: v0.17.0
    hooks:
      - id: yamlfmt
        args: ['-conf', './.config/yamlfmt.yaml']
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: ['--strict', '-c', './.config/yamllint.yaml']
  - repo: local
    hooks:
      - name: shellcheck
        id: shellcheck
        description: Test shell scripts with shellcheck
        entry: mise exec -E dev -- shellcheck
        language: python
        types: [shell]
        require_serial: true
  # Git Hooks
  - repo: https://github.com/compilerla/conventional-pre-commit.git
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
