[project]
name = "alekbuza-github-io"
version = "1.0.0"
description = "Personal Website"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = ["pre-commit>=4.3.0"]
