---
name: github-pages
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - main
env:
  MISE_ENV: "dev"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: jdx/mise-action@v3
        with:
          cache: true
          log_level: debug
      - run: mise run hugo:build
      - uses: actions/upload-pages-artifact@v4
        with:
          path: src/public
          retention-days: 1
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
